#!/bin/bash
[[ ! -n "${DTOKEN}" ]] || [[ ! -n "${DAPPID}" ]] && echo "Running outside module, exitting..." && exit 1

script_dir="$(dirname "$0")"

md5_song=$(echo "$(cmus-remote -Q | grep file | cut -c 6-)" | md5sum | awk '{print $1}')

asset_array=$(curl --silent -X GET \
  -H "Content-Type: application/json" \
  -H "Authorization: ${DTOKEN}" \
  https://canary.discord.com/api/v9/oauth2/applications/${DAPPID}/assets)

asset_count=$(jq  <<< "$asset_array" length)
asset_random=$(jq <<< "$asset_array" ".[$(shuf -i 0-${asset_count} -n 1)]")

[[ $asset_count -lt 290 ]] && exit 0

while [[ "${md5_song}" = "$(jq <<< "$asset_random" .name | sed 's/"//g')" ]]; do
  asset_random=$(jq <<< "$asset_array" ".[$(shuf -i 0-${asset_count} -n 1)]")
done

(curl --silent -X DELETE \
  -H "Authorization: ${DTOKEN}" \
  https://canary.discord.com/api/v9/oauth2/applications/${DAPPID}/assets/$(jq <<< "$asset_random" .id | sed 's/"//g')
) && (
  rm -f "${script_dir}/covers/$(jq <<< "$asset_random" .id | sed 's/"//g')"
  exit 0
) || exit 1

