#!/bin/sh
for mod in "$(dirname "$0")"/modules/*.drpc; do
	. "$mod"
done

while :; do
	m_mpris="$(f_mpris)"
	m_mpris="$(echo "$m_mpris" | awk '{$1=$1};1')"

	# if [ -n "$DEBUG" ]; then
	# 	echo "${m_mpris}" | jq -r .hash
	# else
		cat <<EOF
	[ \
	    { \
	        "application_id": ${CONF_DISCORD_APPID}, \
	        "state": "🎵: $(echo "${m_mpris}" | jq -r .pretty)", \
	        "details": "👀: $(f_wl_active_app)", \
	        "large_image": { \
	            "key": "$(echo "${m_mpris}" | jq -r .hash)", \
	            "text": "$(echo "${m_mpris}" | jq -r .artist) - $(echo "${m_mpris}" | jq -r .title | sed "s/'/\\\'/g")" \
	        }, \
	        "small_image": null, \
	        "buttons": [] \
	    } \
	]
EOF
	# fi

	sleep "${CONF_INTERVAL:-1}"
done
